Add LSAT verification logic, Implement response logic for valid LSAT
DhananjayPurohit/LSAT-Go-proxy pull request #5
Opened 2022-06-18 17:59 UTC by DhananjayPurohit

Added LSAT verification logic (signature verification and paymentHash should be equal to hash of preimage) and also implemented response logic for valid LSAT

2022-06-20 14:39 UTC, bumi commented on main.go
>  	authField, authFieldIsPresent := c.Request.Header["Authorization"]
maybe we can parse this header and extract the macaroon and the preimage in a utils function.

e.g. 
```
macaroon, preimage, err = utils.parseLsatHeader(c.Request.Header["Authorization"])
```
then we don't need to do the TrimSpace and such in the different methods.

2022-06-21 09:12 UTC, kiwiidb requested changes
2 main things needed:

- inject the rootkey instead of hard-coding it
- refactor the conditional logic in the `getProtectedResource` endpoint

2022-06-21 09:12 UTC, kiwiidb commented on main.go
> +	mintMacaroon "proxy/macaroon"
better alias would be `macaroonutils`

2022-06-21 09:12 UTC, kiwiidb commented on main.go
> +	var IsValidMacaroon bool = false
```
isValidMacaroon := false
```

2022-06-21 09:12 UTC, kiwiidb commented on main.go
> +	if authFieldIsPresent && IsValidLSAT {
I'm pretty sure `authFieldIsPresent` always is `true` here. You could return the protected content on line 42, and then you can get rid of all the `if` blocks.

2022-06-22 15:36 UTC, merged